"""
Real-time interception: hooks into HuggingFace generate() and audits
output in sentence-sized chunks AS THE MODEL GENERATES.

This is the feature that makes the original v1 vision literally true:
errors are caught mid-generation, before the full document exists.
"""
from sentinel.engine import SentinelEngine


class StreamingSentinel:
    def __init__(self, engine: SentinelEngine):
        self.engine = engine

    def generate_guarded(self, model, tokenizer, prompt: str,
                         max_new_tokens: int = 300, **gen_kwargs):
        """
        Generates sentence-by-sentence. After each sentence completes,
        it is audited BEFORE being appended to the visible output.
        Flagged sentences are withheld and reported, not shown silently.
        """
        import torch
        generated_ids = tokenizer(prompt, return_tensors="pt")
        output_text = ""
        flagged = []
        buffer = ""
        eos = tokenizer.eos_token_id

        for _ in range(max_new_tokens // 10):
            out = model.generate(
                **generated_ids, max_new_tokens=10, do_sample=True,
                pad_token_id=eos, **gen_kwargs
            )
            new_tokens = out[0][generated_ids["input_ids"].shape[1]:]
            new_text = tokenizer.decode(new_tokens, skip_special_tokens=True)
            generated_ids = {"input_ids": out}
            buffer += new_text
            output_text += new_text

            # audit when a sentence boundary is reached
            while ". " in buffer or "! " in buffer or "? " in buffer:
                idx = max(buffer.find(". "), buffer.find("! "), buffer.find("? ")) + 1
                sentence, buffer = buffer[:idx], buffer[idx:]
                result = self.engine.audit(sentence)
                for d in result.detections:
                    if d.severity != "review":
                        flagged.append(d)

        return {
            "text": output_text,
            "flagged_during_generation": flagged,
            "note": ("Flagged sentences were generated by the model but are "
                     "reported here rather than silently trusted."),
        }
